version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    container_name: voiture-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compagnie
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - voiture-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: voiture-backend
    ports:
      - "8065:8065"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/compagnie
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mariadb
    networks:
      - voiture-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: voiture-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - voiture-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - voiture-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - voiture-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadminjava
    ports:
      - "8070:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - voiture-network
    restart: unless-stopped

networks:
  voiture-network:
    driver: bridge

volumes:
  mariadb-data:
  prometheus-data:
  grafana-data: