global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend:8065']
        labels:
          application: 'magasin-voiture'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']